create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,name text not null default '',phone text default '',country text default '',city text default '',avatar_url text default '',created_at timestamptz not null default now());
create table if not exists public.listings(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete set null,type text not null check(type in('product','service')),title text not null,description text default '',price numeric(14,2) default 0,currency text not null default 'USD',category text default '',country text default '',location text default '',contact text default '',image_url text default '',quantity integer default 1,status text not null default 'active',created_at timestamptz not null default now());
create table if not exists public.businesses(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete set null,name text not null,category text not null default '',description text default '',phone text default '',whatsapp text default '',country text default '',address text default '',location text default '',image_url text default '',rating numeric(3,2) not null default 0,review_count integer not null default 0,created_at timestamptz not null default now());
create table if not exists public.favorites(user_id uuid references auth.users(id) on delete cascade,listing_id uuid references public.listings(id) on delete cascade,created_at timestamptz not null default now(),primary key(user_id,listing_id));
create table if not exists public.reviews(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete set null,business_id uuid references public.businesses(id) on delete cascade,rating integer not null check(rating between 1 and 5),comment text default '',created_at timestamptz not null default now());
create table if not exists public.messages(id uuid primary key default gen_random_uuid(),sender_id uuid references auth.users(id) on delete set null,receiver_id uuid references auth.users(id) on delete set null,body text not null,created_at timestamptz not null default now());
create index if not exists listings_created_idx on public.listings(created_at desc);
create index if not exists listings_type_idx on public.listings(type);
create index if not exists businesses_created_idx on public.businesses(created_at desc);
create index if not exists messages_sender_idx on public.messages(sender_id);
create index if not exists messages_receiver_idx on public.messages(receiver_id);
alter table public.profiles enable row level security; alter table public.listings enable row level security; alter table public.businesses enable row level security; alter table public.favorites enable row level security; alter table public.reviews enable row level security; alter table public.messages enable row level security;
drop policy if exists "profiles self" on public.profiles; create policy "profiles self" on public.profiles for all to authenticated using(auth.uid()=id) with check(auth.uid()=id);
drop policy if exists "public active listings" on public.listings; create policy "public active listings" on public.listings for select using(status='active');
drop policy if exists "listing insert" on public.listings; create policy "listing insert" on public.listings for insert to authenticated with check(auth.uid()=user_id);
drop policy if exists "listing owner update" on public.listings; create policy "listing owner update" on public.listings for update to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists "listing owner delete" on public.listings; create policy "listing owner delete" on public.listings for delete to authenticated using(auth.uid()=user_id);
drop policy if exists "public businesses" on public.businesses; create policy "public businesses" on public.businesses for select using(true);
drop policy if exists "business insert" on public.businesses; create policy "business insert" on public.businesses for insert to authenticated with check(auth.uid()=user_id);
drop policy if exists "business owner update" on public.businesses; create policy "business owner update" on public.businesses for update to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists "favorites own" on public.favorites; create policy "favorites own" on public.favorites for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists "public reviews" on public.reviews; create policy "public reviews" on public.reviews for select using(true);
drop policy if exists "review insert" on public.reviews; create policy "review insert" on public.reviews for insert to authenticated with check(auth.uid()=user_id);
drop policy if exists "messages visible" on public.messages; create policy "messages visible" on public.messages for select to authenticated using(auth.uid()=sender_id or auth.uid()=receiver_id);
drop policy if exists "message insert" on public.messages; create policy "message insert" on public.messages for insert to authenticated with check(auth.uid()=sender_id);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,name) values(new.id,coalesce(new.raw_user_meta_data->>'name','')); return new; exception when unique_violation then return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
